version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: educ_prog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: "/var/lib/postgresql/data/"
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "127.0.0.1:5433:5432"
