spring:
  application:
    name: uisupTest
  datasource:
    url: jdbc:postgresql://dpg-cvt7bere5dus73a38vl0-a.frankfurt-postgres.render.com/uisupdb?sslmode=require
    username: uisupuser
    password: dJ3TX54EOY6Um4cTV0OdkiTUZyOa1nqA
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085

admin:
  username: main_admin
  password: admin312!
