spring:
  application:
    name: uisupTest
  datasource:
    url: postgresql://uisupuser:dJ3TX54EOY6Um4cTV0OdkiTUZyOa1nqA@dpg-cvt7bere5dus73a38vl0-a.frankfurt-postgres.render.com/uisupdb
    username: uisupuser
    password: dJ3TX54EOY6Um4cTV0OdkiTUZyOa1nqA
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: true


server:
  port: 8085

admin:
  username: main_admin
  password: admin312!
